version: '3.3'
services:

  zipkin:
    image: openzipkin/zipkin
    networks:
      - front_net
      - back_net
    ports:
      - "9411:9411"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    ports:
      - "5601:5601"

networks:
  front_net:
    external:
      name: docker_front_net
  back_net:
    external:
      name: docker_back_net

